//! Buchberger algorithm — Gröbner basis driver.
//!
//! Given a finite set of generators `F = {f₁, …, fₘ}` ⊆
//! `GF(2)[x₀, …, xₙ₋₁]`, the function [`buchberger`] returns a
//! Gröbner basis of the ideal `⟨F⟩` under the polynomial set's
//! shared monomial order.
//!
//! Algorithm (textbook Cox/Little/O'Shea §2.7):
//!
//! 1. Start with `G = F` and the pair list `P = {(i, j) | i < j}`.
//! 2. While `P` is non-empty:
//!    - Pop a pair `(i, j)` under the *normal selection strategy*
//!      (smallest `lcm(lm(gᵢ), lm(gⱼ))` under the basis order).
//!    - Skip the pair when `lm(gᵢ)` and `lm(gⱼ)` are coprime
//!      (Buchberger Criterion 1).
//!    - Compute `S(gᵢ, gⱼ)` and reduce it modulo `G`.
//!    - If the remainder is non-zero, append it to `G` and pair
//!      it with every existing basis element.
//! 3. Return `G`.
//!
//! In GF(2) the field equation `xᵢ² = xᵢ` is already baked into
//! the polynomial representation (every monomial is squarefree),
//! so callers who want to compute the radical ideal closure must
//! add the field equations `xᵢ² + xᵢ = xᵢ` themselves as
//! generators.  In the SAT setting that comes for free because
//! every variable that appears in a clause carries its own field
//! equation generator added by the encoder.
//!
//! The output is **not** the reduced Gröbner basis — that's a
//! follow-up cleanup pass (drop divisible leading monomials,
//! interreduce).  For the UNSAT-by-constant-`1` decision the
//! unreduced basis is sufficient: the constant `1` lives in the
//! ideal iff it shows up as a leading monomial of one of the
//! generators, and `reduce_basis_to_minimal` (next commit, step
//! 5/5) handles the cleanup + SAT encoding wiring.

use crate::polynomial::Polynomial;
use crate::reduction::{monomials_coprime, reduce, s_polynomial};

/// Compute a Gröbner basis of the ideal generated by `generators`
/// under the shared monomial order.  Returns an owned basis
/// vector; the input vector is left untouched.
///
/// The algorithm is the classical Buchberger driver with
/// Criterion 1 (coprime-leading-monomial skip) and the normal
/// selection strategy (smallest pair-lcm wins next).  Termination
/// is guaranteed by Dickson's Lemma; the worst-case running time
/// is doubly exponential in `n_vars`, but on the Boolean ideals
/// the SAT encoder produces (field equations pin every variable to
/// `{0, 1}`) the practical cost is far smaller.
///
/// **Panics** if the input vector is empty (every polynomial in
/// `generators` is needed to derive `n_vars` and the monomial
/// order).  Callers with no constraints should encode the SAT
/// instance as `[Polynomial::zero(n, ord)]` instead.
pub fn buchberger(generators: &[Polynomial]) -> Vec<Polynomial> {
    assert!(
        !generators.is_empty(),
        "buchberger: cannot derive ring shape from an empty generator list",
    );
    let n_vars = generators[0].n_vars();
    let order = generators[0].order();
    for g in generators.iter() {
        debug_assert_eq!(g.n_vars(), n_vars);
        debug_assert_eq!(g.order(), order);
    }

    let mut basis: Vec<Polynomial> = generators.to_vec();
    let mut pairs: Vec<(usize, usize)> = Vec::new();
    for i in 0..basis.len() {
        for j in (i + 1)..basis.len() {
            pairs.push((i, j));
        }
    }

    while !pairs.is_empty() {
        // Normal selection: pop the pair whose lcm of leading
        // monomials is smallest under `order`.  Falls back to
        // "first non-trivial pair" for the rare cases where two
        // pairs share the same lcm.
        let mut best_idx = 0usize;
        let mut best_lcm: Option<crate::monomial::Monomial> = None;
        for (k, &(i, j)) in pairs.iter().enumerate() {
            let lm_i = match basis[i].leading_monomial() {
                Some(m) => m,
                None => continue,
            };
            let lm_j = match basis[j].leading_monomial() {
                Some(m) => m,
                None => continue,
            };
            let lcm = lm_i.lcm(lm_j);
            match &best_lcm {
                None => {
                    best_lcm = Some(lcm);
                    best_idx = k;
                }
                Some(prev) => {
                    if lcm.cmp_with(prev, order) == std::cmp::Ordering::Less {
                        best_lcm = Some(lcm);
                        best_idx = k;
                    }
                }
            }
        }
        let (i, j) = pairs.swap_remove(best_idx);

        // Criterion 1: coprime leading monomials → S-polynomial
        // is guaranteed to reduce to zero.  Skip without
        // computing.
        let lm_i_opt = basis[i].leading_monomial().cloned();
        let lm_j_opt = basis[j].leading_monomial().cloned();
        if let (Some(lm_i), Some(lm_j)) = (&lm_i_opt, &lm_j_opt)
            && monomials_coprime(lm_i, lm_j)
        {
            continue;
        }

        let spoly = s_polynomial(&basis[i], &basis[j]);
        let remainder = reduce(&spoly, &basis);
        if !remainder.is_zero() {
            let new_idx = basis.len();
            // Add new pairs (new_idx, k) for every existing k.
            for k in 0..new_idx {
                pairs.push((k, new_idx));
            }
            basis.push(remainder);
        }
    }

    basis
}

/// Returns `true` iff the constant polynomial `1` lives in the
/// ideal generated by `basis`.  This is the Hilbert Weak
/// Nullstellensatz UNSAT-decision criterion for `GF(2)` —
/// equivalent to "the ideal is the whole ring", equivalent to
/// "the variety `V(I)` is empty", equivalent to UNSAT in the SAT
/// encoding.
///
/// Implementation: `1` is in the ideal iff *some* basis element
/// reduces to `1` (or is `1` itself).  Equivalently, when the
/// Gröbner basis has been computed, `1 ∈ I` iff one of the basis
/// elements *equals* the constant `1` (the reduced basis form
/// makes this even more direct — but the unreduced basis from
/// `buchberger` is enough for the decision).
pub fn contains_one(basis: &[Polynomial]) -> bool {
    basis.iter().any(|g| g.is_one())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::monomial::{Monomial, MonomialOrder};

    fn m(exps: &[u8]) -> Monomial {
        Monomial::from_exponents(exps)
    }

    fn p(monomials: Vec<&[u8]>, n_vars: usize) -> Polynomial {
        Polynomial::from_monomials(
            n_vars,
            MonomialOrder::Grevlex,
            monomials.into_iter().map(m),
        )
    }

    /// Field equation `x² + x = 0` (≡ `x + x = 0` post squarefree
    /// ≡ `0`).  In the SAT encoding the squarefree representation
    /// means every variable's field equation collapses to zero
    /// once it goes through `Polynomial::from_monomials`, so this
    /// helper is only here for the unit-test ergonomics — the
    /// production encoder threads field equations differently.
    fn field_eq(_n_vars: usize, _i: usize) -> Polynomial {
        // After squarefree:  x² + x = x + x = 0.  Return zero
        // explicitly to skip a useless basis element.
        Polynomial::zero(_n_vars, MonomialOrder::Grevlex)
    }

    #[test]
    fn buchberger_identity_on_singleton() {
        // Single generator → already a Gröbner basis.
        let f = p(vec![&[1, 0], &[0, 1]], 2);
        let basis = buchberger(&[f.clone()]);
        assert_eq!(basis.len(), 1);
        assert_eq!(basis[0], f);
        assert!(!contains_one(&basis));
    }

    #[test]
    fn buchberger_skips_coprime_pairs() {
        // {x, y} have coprime leading monomials → no S-poly
        // reduction → basis stays {x, y}.
        let x = p(vec![&[1, 0]], 2);
        let y = p(vec![&[0, 1]], 2);
        let basis = buchberger(&[x.clone(), y.clone()]);
        assert_eq!(basis.len(), 2);
        assert!(basis.contains(&x));
        assert!(basis.contains(&y));
        assert!(!contains_one(&basis));
    }

    #[test]
    fn buchberger_detects_contradiction_via_constant_one() {
        // Encode the trivial Boolean UNSAT `x ∧ ¬x` over a single
        // variable `x₀`.
        //   "x" as a polynomial: `x`.
        //   "¬x" as `1 - x` = `x + 1` over GF(2).
        // Adding them: x + (x + 1) = 1.  Buchberger should reach
        // `1` in the basis.
        let x = p(vec![&[1]], 1);
        let neg_x = p(vec![&[1], &[0]], 1); // x + 1
        let basis = buchberger(&[x.clone(), neg_x.clone()]);
        assert!(contains_one(&basis), "expected `1` in basis: got {basis:?}");
    }

    #[test]
    fn buchberger_consistent_pair_stays_satisfiable() {
        // Encode the consistent system `x = 0, y = 0` as
        // generators `x` and `y` (each says "must equal 0").
        // No constraint forces inconsistency → `1` not in basis.
        let x = p(vec![&[1, 0]], 2);
        let y = p(vec![&[0, 1]], 2);
        let basis = buchberger(&[x, y]);
        assert!(!contains_one(&basis));
    }

    #[test]
    fn buchberger_zero_field_eq_helper_does_not_corrupt_basis() {
        // Sanity check that adding a zero polynomial as a
        // generator (mirroring how field_eq collapses in GF(2)
        // squarefree representation) doesn't make `1` appear
        // erroneously.
        let x = p(vec![&[1, 0]], 2);
        let z = field_eq(2, 0);
        let basis = buchberger(&[x.clone(), z]);
        assert!(!contains_one(&basis));
    }
}
